# Generated by Django 5.2.8 on 2025-11-12 02:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Optional: Google Maps embed URL to show your exact location.'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='region',
            field=models.CharField(blank=True, help_text='Region or county where the company is based.', max_length=255),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='positions_available',
            field=models.PositiveIntegerField(default=1, help_text='Number of attachment slots available.'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='region',
            field=models.CharField(blank=True, help_text='Region for this vacancy (if different from company HQ).', max_length=255),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='start_date',
            field=models.DateField(blank=True, help_text='Preferred attachment start date.', null=True),
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hub.companyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
