# Generated by Django 5.2.8 on 2025-11-12 03:25

import django.core.validators
import django.db.models.deletion
import hub.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_companyprofile_map_embed_url_companyprofile_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Admin'), ('MODERATOR', 'Moderator'), ('COMPANY', 'Company Representative'), ('STUDENT', 'Student / General User')], default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(help_text='City or town', max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('work_location_type', models.CharField(choices=[('ONSITE', 'Onsite'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=10)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('FREELANCE', 'Freelance'), ('INTERN', 'Internship')], default='FULL_TIME', max_length=12)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry-Level'), ('MID', 'Mid-Level'), ('SENIOR', 'Senior'), ('EXEC', 'Executive')], default='ENTRY', max_length=6)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(choices=[('KES', 'KES'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='KES', max_length=3)),
                ('responsibilities', models.TextField(blank=True, help_text='5–10 bullet points')),
                ('benefits', models.TextField(blank=True)),
                ('application_deadline', models.DateField(blank=True, help_text='Optional; can be longer than 14 days or left blank for open until filled', null=True)),
                ('easy_apply', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='hub.companyprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_snapshot', models.FileField(blank=True, null=True, upload_to='app_resumes/')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW', 'Interviewing'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='APPLIED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hub.jobpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('education_history', models.TextField(blank=True, help_text='List institutions, dates, awards.')),
                ('work_experience', models.TextField(blank=True, help_text='List roles, companies, dates, responsibilities.')),
                ('default_cover_letter', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=hub.models.upload_cv_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['title'], name='hub_jobpost_title_be6786_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['experience_level'], name='hub_jobpost_experie_290d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['job_type'], name='hub_jobpost_job_typ_8c43c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'student')},
        ),
    ]
