# Generated by Django 5.2.8 on 2025-11-12 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_alter_user_role_jobpost_jobapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='agree_at_will',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='certify_truth',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ApplicationCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('valid_through', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='hub.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationCriminalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_unspent_convictions', models.BooleanField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criminal_history', to='hub.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree_or_diploma', models.CharField(blank=True, max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('start_year', models.CharField(blank=True, max_length=10)),
                ('end_year', models.CharField(blank=True, max_length=10)),
                ('graduated', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='hub.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('ethnicity', models.CharField(blank=True, max_length=100)),
                ('veteran_status', models.CharField(blank=True, max_length=100)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eeo', to='hub.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(blank=True, max_length=255)),
                ('company_phone', models.CharField(blank=True, max_length=50)),
                ('job_title', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=255)),
                ('reason_for_leaving', models.CharField(blank=True, max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='hub.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_legal_name', models.CharField(max_length=255)),
                ('previous_names', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('eligible_to_work', models.BooleanField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('preferred_schedule', models.CharField(blank=True, max_length=255)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='hub.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hub.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(blank=True, max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='hub.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='hub.jobapplication')),
            ],
        ),
    ]
