# Generated by Django 5.2.8 on 2025-11-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_jobapplication_agree_at_will_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='standard_apply',
            field=models.BooleanField(default=False),
        ),
    ]
